[project]
name = "PIaaS"
version = "0.0.1"
description = "PI as a Service bare metal cloud Frontend UI"
readme = "README.md"
dependencies = [
    "flask",
]
[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
